# Prefect deployment configuration
# Place this file in your project root directory

# Build step - how to prepare your code for deployment
build: null

# Push step - where to store your code (not needed for local)
push: null

# Pull step - how workers retrieve your code
pull:
  - prefect.deployments.steps.set_working_directory:
      directory: /app

# Deployments
deployments:
  - name: ml-pipeline-production
    version: "1.0.0"
    tags:
      - ml
      - fake-news
      - production
    description: Complete ML pipeline for fake news detection
    entrypoint: prefect_flows/ml_pipeline_flow.py:ml_pipeline_flow
    work_pool:
      name: default-agent-pool
    parameters:
      data_path: "/app/data/fake_news.csv"
      model_name: "roberta-base"
      epochs: 3
      batch_size: 8
      learning_rate: 0.00002
      mlflow_uri: "http://mlflow:5000"
    
    # Uncomment to add schedule
    # schedules:
    #   - cron: "0 2 * * *"
    #     timezone: "UTC"

  - name: ml-pipeline-quick-test
    version: "1.0.0"
    tags:
      - ml
      - test
    description: Quick test run with sample data
    entrypoint: prefect_flows/ml_pipeline_flow.py:ml_pipeline_flow
    work_pool:
      name: default-agent-pool
    parameters:
      data_path: "/app/data/fake_news.csv"
      sample_size: 1000
      model_name: "roberta-base"
      epochs: 1
      batch_size: 8
      learning_rate: 0.00002
      mlflow_uri: "http://mlflow:5000"